version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: pogreb
      POSTGRES_USER: userok
      POSTGRES_PASSWORD: p@ssw0rd
    networks:
      - overlay
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    container_name: pg_admin
    networks:
      - overlay
    ports:
      - "8080:8080"

  rabbitmq:
    image: rabbitmq:3.11.0-management
    restart: always
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: userok
      RABBITMQ_DEFAULT_PASS: p@ssw0rd
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq

volumes:
  db-data:
  rabbitmq:

networks:
  overlay:
