spring:
  rabbitmq:
    host: localhost
    username: userok
    password: p@ssw0rd
    port: 5672

server:
  port: 8001

telegram:
  bot:
    name: pogreb_tbot
    token: 6223994235:AAHtZMTkBibqUfm0M8DW_WxiPCqyOe_diN8
