server:
  ssl:
    enabled: false

spring:
  rabbitmq:
    host: localhost
    username: userok
    password: p@ssw0rd
    port: 5672

telegram:
  bot:
    username: pogreb_tbot
    url: 07a9-195-170-179-37.eu.ngrok.io
    path: /update

