server:
  port: 8004

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: myjavasender@gmail.com
    password: qwerty00777
    properties:
      protocol: smtp
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

service:
  activate:
    uri: http://127.0.0.1:8003/mail/activate?id={id}
