server:
  port: 8002

spring:
  rabbitmq:
    host: localhost
    username: userok
    password: p@ssw0rd
    port: 5672
  datasource:
    url: jdbc:postgresql://localhost:5432/pogreb
    username: userok
    password: p@ssw0rd
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

telegram:
  bot:
    token: 6223994235:AAHtZMTkBibqUfm0M8DW_WxiPCqyOe_diN8
    api:
      url: https://api.telegram.org/
