spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pogreb
    username: userok
    password: p@ssw0rd
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mvc:
    problemdetails:
      enabled: true
